import type { ThemeFile } from './theme-types';

/**
 * Emergency fallback theme — used only when all JSON loading fails.
 * Keep in sync with reasonance-dark.json.
 * NOTE: Uses literal values (no var() references) because
 * it must work standalone without any other variables being set.
 */
export const FALLBACK_THEME: ThemeFile = {
  meta: {
    name: 'Fallback Dark',
    author: 'Reasonance Team',
    version: '1.0.0',
    description: 'Emergency fallback theme for recovery',
    type: 'theme',
    colorScheme: 'dark',
    editorTheme: 'forge-dark',
    schemaVersion: 1,
  },
  colors: {
    '--bg-primary': '#121212',
    '--bg-secondary': '#1a1a1a',
    '--bg-tertiary': '#2a2a2a',
    '--bg-hover': 'rgba(255, 255, 255, 0.06)',
    '--bg-surface': '#161616',
    '--border': '#5a5a5a',
    '--text-primary': '#f0f0f0',
    '--text-body': '#d4d4d4',
    '--text-secondary': '#a3a3a3',
    '--text-muted': '#b0b0b0',
    '--accent': '#3b82f6',
    '--accent-text': '#93bbfc',
    '--accent-hover': '#2563eb',
    '--accent-statusbar': '#1e40af',
    '--danger': '#ef4444',
    '--danger-dark': '#991b1b',
    '--danger-text': '#fca5a5',
    '--success': '#16a34a',
    '--success-text': '#4ade80',
    '--warning': '#ca8a04',
    '--warning-text': '#fbbf24',
    '--accent-btn': '#1e40af',
    '--danger-btn': '#991b1b',
    '--text-on-accent': '#ffffff',
    '--code-bg': 'oklch(0.18 0.02 240)',
    '--code-accent': 'oklch(0.78 0.18 320)',
  },
  hues: {
    '--hue-accent': 220,
    '--hue-danger': 25,
    '--hue-success': 145,
    '--hue-warning': 85,
    '--hue-state-retry': 45,
  },
  states: {
    '--state-idle': 'oklch(0.55 0.00 0)',
    '--state-idle-text': 'oklch(0.72 0.00 0)',
    '--state-queued': '#ca8a04',
    '--state-queued-text': '#fbbf24',
    '--state-running': '#3b82f6',
    '--state-running-text': '#93bbfc',
    '--state-success': '#16a34a',
    '--state-success-text': '#4ade80',
    '--state-failed': '#ef4444',
    '--state-failed-text': '#fca5a5',
    '--state-retrying': 'oklch(0.65 0.18 45)',
    '--state-retrying-text': 'oklch(0.78 0.15 45)',
  },
  'ui-states': {
    '--text-disabled': 'oklch(0.55 0.00 0)',
    '--bg-disabled': 'oklch(0.25 0.00 0)',
    '--border-disabled': 'oklch(0.35 0.00 0)',
    '--bg-selected': 'oklch(0.30 0.08 220)',
    '--text-selected': '#f0f0f0',
    '--text-placeholder': 'oklch(0.55 0.00 0)',
    '--focus-ring-color': 'oklch(0.70 0.20 220)',
  },
  typography: {
    '--font-ui':
      "'Atkinson Hyperlegible Next', 'Noto Sans SC', 'Noto Sans Devanagari', 'Microsoft YaHei', 'PingFang SC', system-ui, -apple-system, sans-serif",
    '--font-mono': "'Atkinson Hyperlegible Mono', monospace",
    '--font-size-sm': '0.875rem',
    '--font-size-base': '1rem',
    '--font-size-md': '1.25rem',
    '--font-size-lg': '1.5rem',
    '--font-size-hero': '2rem',
    '--font-size-xs': '0.7rem',
    '--font-size-small': '0.875rem',
    '--font-size-tiny': '0.875rem',
    '--font-size-code': '1rem',
    '--line-height-sm': 1.6,
    '--line-height-base': 1.5,
    '--line-height-md': 1.4,
    '--line-height-lg': 1.3,
    '--line-height-hero': 1.2,
    '--measure': '72ch',
    '--font-weight-sm': 500,
    '--font-weight-base': 500,
    '--font-weight-ui': 400,
    '--font-weight-md': 700,
    '--font-weight-lg': 700,
    '--font-weight-hero': 800,
    '--font-weight-body': 500,
    '--font-weight-heading': 800,
    '--line-height': '1.5',
    '--letter-spacing': 'normal',
    '--word-spacing': 'normal',
  },
  spacing: {
    '--space-1': '0.25rem',
    '--space-2': '0.5rem',
    '--space-3': '0.75rem',
    '--space-4': '1rem',
    '--space-5': '1.5rem',
    '--space-6': '2rem',
    '--inset-component': '0.75rem',
    '--inset-section': '1rem',
    '--stack-tight': '0.25rem',
    '--stack-normal': '0.5rem',
    '--stack-loose': '1rem',
    '--interactive-gap': '0.5rem',
    '--paragraph-spacing': 'calc(1.5 * 1.5em)',
    '--btn-padding': '0.5rem 0.75rem',
    '--btn-padding-sm': '0.25rem 0.5rem',
    '--panel-padding': '1rem',
  },
  borders: {
    '--border-width': '2px',
    '--border-style': 'solid',
    '--border-color': '#5a5a5a',
    '--radius': 0,
    '--radius-full': '50%',
  },
  focus: {
    '--focus-ring': '2px solid #3b82f6',
    '--focus-offset': '2px',
  },
  transitions: {
    '--transition-fast': '0.1s ease',
    '--transition-normal': '0.2s ease',
    '--toast-duration': '5s',
  },
  layout: {
    '--toolbar-height': '44px',
    '--statusbar-height': '28px',
  },
  layers: {
    '--layer-base': 0,
    '--layer-raised': 10,
    '--layer-sticky': 100,
    '--layer-overlay': 500,
    '--layer-dropdown': 1000,
    '--layer-modal': 2000,
    '--layer-toast': 5000,
    '--layer-top': 9999,
  },
  shadows: {
    '--shadow-sm': '0 1px 3px rgba(0, 0, 0, 0.4)',
    '--shadow-md': '0 4px 12px rgba(0, 0, 0, 0.3)',
    '--shadow-lg': '0 20px 60px rgba(0, 0, 0, 0.5)',
    '--shadow-overlay': '-4px 0 16px rgba(0, 0, 0, 0.3)',
  },
  overlays: {
    '--overlay-bg': 'rgba(0, 0, 0, 0.5)',
    '--overlay-border': 'var(--border)',
  },
  highlights: {
    '--highlight-subtle': 'rgba(255, 255, 255, 0.03)',
    '--highlight-hover': 'rgba(255, 255, 255, 0.06)',
    '--diff-add-bg': 'rgba(22, 163, 74, 0.1)',
    '--diff-remove-bg': 'rgba(220, 38, 38, 0.1)',
    '--terminal-selection': 'rgba(29, 78, 216, 0.4)',
  },
};
